CREATE TABLE USER
(
  ID        BIGINT PRIMARY KEY NOT NULL,
  EMAIL     VARCHAR(255),
  FIRSTNAME VARCHAR(255),
  LASTNAME  VARCHAR(255),
  PASSWORD  VARCHAR(255)
);
CREATE UNIQUE INDEX UK_E6GKQUNXAJVYXL5UCTPL2VL2P_INDEX_2
  ON USER (EMAIL);
CREATE TABLE NOTEBOOK
(
  ID          BIGINT PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(255),
  TITLE       VARCHAR(255)       NOT NULL,
  USER_ID     BIGINT             NOT NULL,
  CONSTRAINT FK8IQODGORYA8O2AWMRBE8EKIIN FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE NOTE
(
  ID          BIGINT PRIMARY KEY NOT NULL,
  BODY        VARCHAR(255),
  TITLE       VARCHAR(255)       NOT NULL,
  NOTEBOOK_ID BIGINT             NOT NULL,
  CONSTRAINT FKLKEGY1FI7Y516JRA1MEFTNP56 FOREIGN KEY (NOTEBOOK_ID) REFERENCES NOTEBOOK (ID) ON DELETE CASCADE
);
CREATE TABLE MARK
(
  ID   BIGINT PRIMARY KEY NOT NULL,
  TYPE VARCHAR(255),
  USER_ID BIGINT NOT NULL
);
CREATE TABLE NOTE_MARK
(
  NOTE_ID BIGINT NOT NULL,
  MARK_ID BIGINT NOT NULL,
  CONSTRAINT FKI6LRBTC18ORCQKBVQGW4I83LI FOREIGN KEY (NOTE_ID) REFERENCES NOTE (ID),
  CONSTRAINT FKP69IYW7RJ51KJOX0FVDOAW68U FOREIGN KEY (MARK_ID) REFERENCES MARK (ID)
);

